### ISSUE TITLE
Eventnews\Hooks\BackendUtility::updateFlexforms(&$params, &$reference) error

### ISSUE THREAD

**Issue by Tonyt8** [cyberhouse/eventnews#16]
Hi Georg,

I am using
Typo3 7.6.11
news 4.3.0
eventnews 1.1.0
php7.0.6

My apologies, I wrongly jumped on a closed thread on the news, so I do correctly here.
I am have a similar problem as chequille had.
Yesterday I tried updating the "news" extension to 5.0.1
My news system failed after the update 5.0.1.
I have a 2 language setup. The category menu would not work any more.
Other things seem to be odd. I tried fixing things, but made a mess of the complete website system.
Anyway I have totally installed the website and started again from the archive files.
The news is working perfect now (version 4.3.0.) I have installed the eventnews 1.1.0 again. I can make eventnews items without any issues. The error warning is shown when I add a page content news system plugin.
How can I fix the issue. I am unsure what you mean above "Fixed in master of eventnews". What is the master? I cannot find a master.
I don't want to risk adding the plugin until the error message is solved, I don't want to repeat the problems I faced yesterday,

Many thanks in advance,
Kind regards,
Tony

The error message I receive:
PHP Warning
Core: Error handler (BE): PHP Warning: Declaration of GeorgRinger\Eventnews\Hooks\BackendUtility::updateFlexforms(&$params, &$reference) should be compatible with GeorgRinger\News\Hooks\BackendUtility::updateFlexforms(array &$dataStructure, array $row) in /kunden/112563_73765/rp-hosting/5005132/6005132/typo3cms/projt3_2pack/typo3conf/ext/eventnews/Classes/Hooks/BackendUtility.php line 0

**Comment by Tonyt8** [comment]
Hi Georg,

I have now installed eventnews 1.1.1, cleared the install tool cache.
I still have this error:

PHP Warning
Core: Error handler (BE): PHP Warning: Declaration of GeorgRinger\Eventnews\Hooks\BackendUtility::updateFlexforms(&$params, &$reference) should be compatible with GeorgRinger\News\Hooks\BackendUtility::updateFlexforms(array &$dataStructure, array $row) in /kunden/112563_73765/rp-hosting/5005132/6005132/typo3cms/projt3_2pack/typo3conf/ext/eventnews/Classes/Hooks/BackendUtility.php line 0

Please can you advise and or help?

Thanks.

Kind regards,
Tony

**Comment by georgringer** [comment]
I doubt that this repository will be maintained anymore as I left the company cyberhouse. use https://github.com/georgringer/eventnews

**Comment by Lobster1956** [comment]
same Problems with eventnews 1.2.0 from the georgringer GIT fork...
https://github.com/cyberhouse/eventnews/issues/17
